Repository Shawntru/Rotten-Tomatillos, pull requests merged in 2020-12, with the labels that each got.

#7 Feature/building homepage
  .eslintcache
  .gitignore
  package-lock.json
  package.json
  src/App.css
  src/App.js
  src/App.scss
  src/MovieCard.js
  src/MovieCard.scss
  src/Movies.js
  src/Movies.scss
  src/Navbar.js
  src/Navbar.scss
  src/_variables.scss
  src/movieData.js
Labels: enhancement

#16 Feature/single movie page
  .eslintcache
  src/App.js
  src/App.scss
  src/MovieCard.js
  src/MovieCard.scss
  src/MovieCard.test.js
  src/MoviePreview.js
  src/MoviePreview.scss
  src/MoviePreview.test.js
  src/Movies.js
  src/Movies.test.js
  src/Navbar.js
  src/Navbar.scss
  src/Navbar.test.js
Labels: enhancement

#18 Feature/api calls
  .eslintcache
  src/App.js
  src/App.scss
  src/ErrorPage/ErrorPage.js
  src/ErrorPage/ErrorPage.scss
  src/MovieCard/MovieCard.js
  src/MovieCard/MovieCard.scss
  src/MovieCard/MovieCard.test.js
  src/MoviePreview.js
  src/MoviePreview/MoviePreview.js
  src/MoviePreview/MoviePreview.scss
  src/MoviePreview/MoviePreview.test.js
  src/Movies/Movies.js
  src/Movies/Movies.scss
  src/Movies/Movies.test.js
  src/Navbar/Navbar.js
  src/Navbar/Navbar.scss
  src/Navbar/Navbar.test.js
  src/apiCalls.js
  src/logo.svg
  src/movieData.js
Labels: enhancement

#25 Feature/creating tests
  .eslintcache
  package-lock.json
  package.json
  src/App.js
  src/App.test.js
  src/ErrorPage/ErrorPage.js
  src/ErrorPage/ErrorPage.test.js
  src/MovieCard/MovieCard.js
  src/MovieCard/MovieCard.test.js
  src/MoviePreview/MoviePreview.js
  src/MoviePreview/MoviePreview.test.js
  src/Movies/Movies.js
  src/Movies/Movies.test.js
  src/Navbar/Navbar.js
  src/Navbar/Navbar.test.js
Labels: Testing, enhancement

#28 Add Router feature to components
  .eslintcache
  package-lock.json
  package.json
  src/App.js
  src/App.test.js
  src/MovieCard/MovieCard.js
  src/MovieCard/MovieCard.test.js
  src/MoviePreview/MoviePreview.js
  src/MoviePreview/MoviePreview.test.js
  src/Movies/Movies.js
  src/Movies/Movies.test.js
  src/apiCalls.js
  src/index.js
Labels: enhancement, refactoring

#29 Fix error handling and error page
  .eslintcache
  src/App.js
  src/ErrorPage/ErrorPage.js
  src/ErrorPage/ErrorPage.scss
  src/MoviePreview/MoviePreview.js
  src/MoviePreview/MoviePreview.scss
  src/apiCalls.js
  src/assets/tomato.png
Labels: refactoring

#30 Feature/add movie trailers
  .eslintcache
  package-lock.json
  package.json
  src/App.js
  src/Movies/Movies.js
  src/Movies/Movies.scss
  src/Navbar/Navbar.js
  src/Navbar/Navbar.scss
  src/TrailerPreview/TrailerPreview.js
  src/TrailerPreview/TrailerPreview.scss
  src/TrailerPreview/TrialerPreview.test.js
  src/apiCalls.js
Labels: accessibility

#32 Feature/trailers in movie preview
  src/MoviePreview/MoviePreview.js
  src/MoviePreview/MoviePreview.scss
  src/Movies/Movies.scss
  src/TrailerPreview/TrailerPreview.js
  src/TrailerPreview/TrailerPreview.scss
Labels: accessibility

#33 Add styling for MovieCard on hover
  src/MovieCard/MovieCard.scss
Labels: accessibility

#34 Feature/search bar
  src/App.js
  src/App.test.js
  src/MovieCard/MovieCard.scss
  src/Movies/Movies.js
  src/Navbar/Navbar.js
  src/Navbar/Navbar.scss
  src/Navbar/Navbar.test.js
  src/assets/search_icon.png
Labels: Testing, accessibility, enhancement

#36 Feature/trailer preview testing suite
  src/TrailerPreview/TrailerPreview.js
  src/TrailerPreview/TrialerPreview.test.js
Labels: Testing

#37 Fix/movie preview test
  src/App.js
  src/MoviePreview/MoviePreview.js
  src/MoviePreview/MoviePreview.test.js
  src/Navbar/Navbar.scss
  src/Navbar/Navbar.test.js
Labels: Testing, refactoring

#40 Feature/refactor tractor
  src/App.js
  src/MoviePreview/MoviePreview.js
  src/Movies/Movies.js
  src/Navbar/Navbar.js
Labels: refactoring

#41 Fix app and moviepreview tests
  src/App.test.js
  src/MoviePreview/MoviePreview.js
  src/MoviePreview/MoviePreview.test.js
Labels: Testing, refactoring

#43 Fix styling to make it more responsive
  src/App.scss
  src/MoviePreview/MoviePreview.js
  src/MoviePreview/MoviePreview.scss
  src/Navbar/Navbar.scss
  src/TrailerPreview/TrailerPreview.scss
Labels: refactoring

#42 Update README.md
  README.md
Labels: documentation

#46 Fix/accessibility
  package-lock.json
  package.json
  src/App/App.js
  src/App/App.scss
  src/App/App.test.js
  src/ErrorPage/ErrorPage.scss
  src/ErrorPage/ErrorPage.test.js
  src/MovieCard/MovieCard.test.js
  src/Navbar/Navbar.js
  src/TrailerPreview/TrailerPreview.test.js
  src/index.js
Labels: bug, refactoring

#48 Add gifs, more info about our project for readme
  README.md
Labels: documentation
